"use strict";
exports.__esModule = true;
var product_1 = require("./product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService;
var result;
result = _productService.getById(2);
var p = new product_1.Product();
p.id = 2;
p.name = 'Iphone11';
p.price = 7000;
p.category = 'Telefon';
_productService.saveProduct(p);
//_productService.deleteProduct(result);
result = _productService.getProduct();
console.log(result);
